apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: resumes
  namespace: {{ .Release.Namespace }}
  labels:
    strimzi.io/cluster: jobs-app
spec:
  partitions: {{ .Values.kafkaTopic.partitions }}
  replicas: 1
  topicName: resumes
